CREATE PROCEDURE binningGroundTruthPrice LANGUAGE SQLSCRIPT AS
BEGIN
	BEGIN
		DECLARE rowNumber integer;
		CREATE TABLE GROUND_TRUTH_BEFORE_BINNING_AIRBNB as (select id, groundTruthPrice from airbnb);
		EXEC 'CREATE INDEX idx ON GROUND_TRUTH_BEFORE_BINNING_AIRBNB (id)';
		
		CREATE TABLE GROUND_TRUTH_AFTER_BINNING_AIRBNB (
			DATA_ID integer primary key,
			BIN_INDEX integer,
			BINNING_DATA integer
		);

		CREATE LOCAL TEMPORARY TABLE #PAL_PARAMETER_TBL (
		    "PARAM_NAME" VARCHAR(256),
		    "INT_VALUE" INTEGER,
		    "DOUBLE_VALUE" DOUBLE,
		    "STRING_VALUE" VARCHAR(1000)
		);
		
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('BINNING_METHOD',1, NULL , NULL);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('SMOOTH_METHOD',0, NULL, NULL);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('BIN_DISTANCE',20, NULL, NULL);
		
		SELECT COUNT(*) INTO rowNumber FROM TABLES WHERE TABLE_NAME = 'PAL_BINNING_MODEL_TBL';
		IF (:rowNumber > 0 ) THEN
			DROP TABLE PAL_BINNING_MODEL_TBL;
		END IF;
		CREATE TABLE PAL_BINNING_MODEL_TBL (
		    "ROW_INDEX" INT,
		    "MODEL_CONTENT" VARCHAR (5000)
		);
		CREATE TABLE PLACEHOLDER1 (
		    "STAT_NAME" VARCHAR(256),
		    "STAT_VALUE" VARCHAR(1000)
		);
				
		BEGIN
			DECLARE gt_before_binning gt_before_binning_T DEFAULT SELECT * FROM GROUND_TRUTH_BEFORE_BINNING_AIRBNB;
			DECLARE gt_after_binning gt_after_binning_T DEFAULT SELECT * FROM GROUND_TRUTH_AFTER_BINNING_AIRBNB;
			DECLARE tmp_param_tbl TABLE LIKE #PAL_PARAMETER_TBL;
			DECLARE lv_placeholder1 TABLE LIKE PLACEHOLDER1;
			DECLARE lv_placeholder2 TABLE LIKE #PAL_PARAMETER_TBL;
			DECLARE binningModel TABLE LIKE PAL_BINNING_MODEL_TBL;
			tmp_param_tbl = SELECT * FROM #PAL_PARAMETER_TBL;
			binningModel = SELECT * FROM PAL_BINNING_MODEL_TBL;
			
			CALL _SYS_AFL.PAL_BINNING(:gt_before_binning, :tmp_param_tbl, gt_binning_values_tbl, binningModel, lv_placeholder1, lv_placeholder2);
			INSERT INTO GROUND_TRUTH_AFTER_BINNING_AIRBNB SELECT * FROM :gt_binning_values_tbl;
			INSERT INTO PAL_BINNING_MODEL_TBL SELECT * FROM :binningModel;
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.groundTruthPrice = GROUND_TRUTH_AFTER_BINNING_AIRBNB.BIN_INDEX FROM AIRBNB INNER JOIN GROUND_TRUTH_AFTER_BINNING_AIRBNB ON AIRBNB.id = GROUND_TRUTH_AFTER_BINNING_AIRBNB.DATA_ID';
			
			DROP TABLE #PAL_PARAMETER_TBL;
			DROP TABLE GROUND_TRUTH_BEFORE_BINNING_AIRBNB;
			DROP TABLE GROUND_TRUTH_AFTER_BINNING_AIRBNB;
			DROP TABLE PLACEHOLDER1;
		END;
	END;
END;