CREATE TABLE AIRBNB (
    id varchar(50) primary key,
    host_response_time varchar(40),
    host_response_rate varchar(20),
    host_is_superhost varchar(5),
    host_neighbourhood varchar(30),
    host_total_listings_count varchar(50),
    host_has_profile_pic varchar(5),
    host_identity_verified varchar(5),
    latitude double,
    longitude double,
    is_location_exact varchar(5),
    property_type varchar(30),
    room_type varchar(30),
    accommodates integer,
    bathrooms varchar(5),
    bedrooms varchar(5),
    beds varchar(5),
    bed_type varchar(30),
    price varchar(30),
    security_deposit varchar(30),
    cleaning_fee varchar(30),
    guests_included integer,
    extra_people varchar(30),
    minimum_nights integer,
    maximum_nights bigint,
    has_availability varchar(2),
    number_of_reviews integer,
    review_scores_rating varchar(50),
    instant_bookable varchar(5),
    is_business_travel_ready varchar(5),
    cancellation_policy varchar(50),
    require_guest_profile_picture varchar(5),
    require_guest_phone_verification varchar(5),
    reviews_per_month varchar(100)
);