--DROP TYPE PAL_MISSING_VALUES_DATA_T;
CREATE TYPE PAL_MISSING_VALUES_DATA_T AS TABLE(
			"ID" INTEGER PRIMARY KEY,
			"HOST_RESPONSE_TIME" VARCHAR(40), 
			"RESPONSE_RATE" INTEGER,
			"HOST_IS_SUPERHOST" VARCHAR(5),
			"HOST_NEIGHBOURHOOD" VARCHAR(30),
			"COUNT_HOST_LISTINGS" INTEGER,
			"HOST_HAS_PROFILE_PIC" VARCHAR(5),
			"HOST_IDENTITY_VERIFIED" VARCHAR(5),
			"NR_BATHROOMS" DOUBLE,
			"NR_BEDROOMS" INTEGER,
			"NR_BEDS" INTEGER,
			"SECURITY_DEPO" DOUBLE,
			"CLEANING_COST" DOUBLE,
			"COST_PER_EXTRA_GUEST" DOUBLE,
			"REVIEW_SCORE" INTEGER,
			"NR_REVIEWS_PER_MONTH" DOUBLE
		);