-- call substitutemissingvalues;

CREATE PROCEDURE substituteMissingValues LANGUAGE SQLSCRIPT AS
BEGIN
	BEGIN
		create table MISSING_VALUES_AIRBNB as
		(select id, host_response_time, response_rate, host_is_superhost, host_neighbourhood, 
			    count_host_listings, host_has_profile_pic, host_identity_verified, nr_bathrooms, nr_bedrooms, nr_beds, security_depo,
			    cleaning_cost, cost_per_extra_guest, review_score, nr_reviews_per_month from AIRBNB);
	    EXEC 'CREATE INDEX idx ON MISSING_VALUES_AIRBNB (id)';
		
		CREATE LOCAL TEMPORARY TABLE #PAL_PARAMETER_TBL (
		    "PARAM_NAME" VARCHAR (256),
		    "INT_VALUE" INTEGER,
		    "DOUBLE_VALUE" DOUBLE,
		    "STRING_VALUE" VARCHAR (1000)
		);
		
		CREATE LOCAL TEMPORARY TABLE #PAL_MISSING_VALUES_NULL_MAP_TBL (
			"COLUMN_NAME" VARCHAR(20),
			"SUBSTITUTE_VALUE" VARCHAR(20),
			"COUNT" INTEGER
		);
		--SELECT * FROM MISSING_VALUES_AIRBNB;
		
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('id', 100, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('host_response_time', 100, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('response_rate', 201, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('host_is_superhost', 101, null, 'f');
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('host_neighbourhood', 100, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('count_host_listings', 100, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('host_has_profile_pic', 101, null, 'f');
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('host_identity_verified', 100, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('nr_bathrooms', 200, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('nr_bedrooms', 201, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('nr_beds', 100, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('security_depo', 200, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('cleaning_cost', 200, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('cost_per_extra_guest', 200, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('review_score', 200, null, null);
		INSERT INTO #PAL_PARAMETER_TBL VALUES ('nr_reviews_per_month', 200, null, null);
		
		CREATE TABLE PAL_NO_MISSING_VALUES_AIRBNB_TBL LIKE MISSING_VALUES_AIRBNB;
		
		BEGIN
			DECLARE missing_values_tbl PAL_MISSING_VALUES_DATA_T DEFAULT SELECT * FROM MISSING_VALUES_AIRBNB;
			DECLARE no_missing_values_tbl PAL_MISSING_VALUES_DATA_T DEFAULT SELECT * FROM PAL_NO_MISSING_VALUES_AIRBNB_TBL;
			DECLARE tmp_param_tbl TABLE LIKE #PAL_PARAMETER_TBL;
			DECLARE stastics TABLE LIKE #PAL_MISSING_VALUES_NULL_MAP_TBL;
			tmp_param_tbl = SELECT * FROM #PAL_PARAMETER_TBL;
			stastics = SELECT * FROM #PAL_MISSING_VALUES_NULL_MAP_TBL;
			
			CALL "_SYS_AFL"."PAL_SUBSTITUTE_MISSING_VALUES"( :missing_values_tbl, :tmp_param_tbl, no_missing_values_tbl, :stastics);
			INSERT INTO PAL_NO_MISSING_VALUES_AIRBNB_TBL SELECT * FROM :no_missing_values_tbl;
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.host_response_time = PAL_NO_MISSING_VALUES_AIRBNB_TBL.host_response_time FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.response_rate = PAL_NO_MISSING_VALUES_AIRBNB_TBL.response_rate FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.host_is_superhost = PAL_NO_MISSING_VALUES_AIRBNB_TBL.host_is_superhost FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.host_neighbourhood = PAL_NO_MISSING_VALUES_AIRBNB_TBL.host_neighbourhood FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.count_host_listings = PAL_NO_MISSING_VALUES_AIRBNB_TBL.count_host_listings FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.host_has_profile_pic = PAL_NO_MISSING_VALUES_AIRBNB_TBL.host_has_profile_pic FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.host_identity_verified = PAL_NO_MISSING_VALUES_AIRBNB_TBL.host_identity_verified FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.nr_bathrooms = PAL_NO_MISSING_VALUES_AIRBNB_TBL.nr_bathrooms FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.nr_bedrooms = PAL_NO_MISSING_VALUES_AIRBNB_TBL.nr_bedrooms FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.nr_beds = PAL_NO_MISSING_VALUES_AIRBNB_TBL.nr_beds FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.security_depo = PAL_NO_MISSING_VALUES_AIRBNB_TBL.security_depo FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.cleaning_cost = PAL_NO_MISSING_VALUES_AIRBNB_TBL.cleaning_cost FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.cost_per_extra_guest = PAL_NO_MISSING_VALUES_AIRBNB_TBL.cost_per_extra_guest FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.review_score = PAL_NO_MISSING_VALUES_AIRBNB_TBL.review_score FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			EXEC 'UPDATE AIRBNB SET AIRBNB.nr_reviews_per_month = PAL_NO_MISSING_VALUES_AIRBNB_TBL.nr_reviews_per_month FROM AIRBNB INNER JOIN PAL_NO_MISSING_VALUES_AIRBNB_TBL ON AIRBNB.id = PAL_NO_MISSING_VALUES_AIRBNB_TBL.id';
			
			DROP TABLE MISSING_VALUES_AIRBNB;
			DROP TABLE #PAL_PARAMETER_TBL;
			DROP TABLE PAL_NO_MISSING_VALUES_AIRBNB_TBL;
			DROP TABLE #PAL_MISSING_VALUES_NULL_MAP_TBL;
		END;
	END;
END;













--DROP TYPE PAL_MISSING_VALUES_DATA_T;
CREATE TYPE PAL_MISSING_VALUES_DATA_T AS TABLE(
			"ID" INTEGER PRIMARY KEY,
			"HOST_RESPONSE_TIME" VARCHAR(40), 
			"RESPONSE_RATE" INTEGER,
			"HOST_IS_SUPERHOST" VARCHAR(5),
			"HOST_NEIGHBOURHOOD" VARCHAR(30),
			"COUNT_HOST_LISTINGS" INTEGER,
			"HOST_IDENTITY_VERIFIED" VARCHAR(5),
			"NR_BATHROOMS" DOUBLE,
			"NR_BEDROOMS" INTEGER,
			"NR_BEDS" INTEGER,
			"SECURITY_DEPO" DOUBLE,
			"CLEANING_COST" DOUBLE,
			"COST_PER_EXTRA_GUEST" DOUBLE,
			"REVIEW_SCORE" INTEGER,
			"NR_REVIEWS_PER_MONTH" DOUBLE
		);